set -e
true
true
/sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/bin/spades-hammer /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/corrected/configs/config.info
/sw/arch/eb/software/Python/3.12.3-GCCcore-13.3.0/bin/python3 /sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/share/spades/spades_pipeline/scripts/compress_all.py --input_file /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/corrected/corrected.yaml --ext_python_modules_home /sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/share/spades --max_threads 8 --output_dir /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/corrected --not_used_yaml_file /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/corrected/dont_correct.yaml --gzip_output
true
true
/sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/bin/spades-core /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K21/configs/config.info
/sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/bin/spades-core /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K33/configs/config.info
/sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/bin/spades-core /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K55/configs/config.info
/sw/arch/eb/software/Python/3.12.3-GCCcore-13.3.0/bin/python3 /sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/share/spades/spades_pipeline/scripts/copy_files.py /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K55/before_rr.fasta /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/before_rr.fasta /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K55/assembly_graph_after_simplification.gfa /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/assembly_graph_after_simplification.gfa /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K55/final_contigs.fasta /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/contigs.fasta /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K55/first_pe_contigs.fasta /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/first_pe_contigs.fasta /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K55/strain_graph.gfa /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/strain_graph.gfa /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K55/scaffolds.fasta /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/scaffolds.fasta /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K55/scaffolds.paths /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/scaffolds.paths /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K55/assembly_graph_with_scaffolds.gfa /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/assembly_graph_with_scaffolds.gfa /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K55/assembly_graph.fastg /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/assembly_graph.fastg /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/K55/final_contigs.paths /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/contigs.paths
true
/sw/arch/eb/software/Python/3.12.3-GCCcore-13.3.0/bin/python3 /sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/scaffolds.fasta --misc_dir /gorilla/home/vico3159/genome_analyses/analyses/09_extra_assembly/spades_hybrid/spades_hybrid_output/misc --threshold_for_breaking_scaffolds 3
true
